# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.avatar_size:
        thumbnail:
            name: thumb
            max_width: 200
            max_height: 200
        super_thumb:
            name: super_thumb
            max_width: 20
            max_height: 20

services:
    app.avatar_upload:
        class: AppBundle\FileUploader
        arguments: ['%upload_dir%']
    app.avatar_resize:
        class: AppBundle\FileResizer
        arguments: ['%upload_dir%', '%app.avatar_size%']
